'use client';
import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function BirthPage() {
  const router = useRouter(); const [error, setError] = useState('');
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); if (!data.birthDate || (!data.birthTime && !data.unknownTime)) { setError('请填写出生日期和时间，或勾选不知道出生时间。'); return; } sessionStorage.setItem('destiny.birth', JSON.stringify(data)); router.push('/report'); }
  return <main className="min-h-screen bg-sand px-6 py-12 text-ink"><div className="mx-auto max-w-2xl"><a href="/" className="text-sm text-jade">← 返回首页</a><h1 className="mt-10 text-4xl font-semibold">先从你的出生资料开始</h1><p className="mt-3 text-slate-600">带 * 为必填项。资料只用于本次本地演示。</p><form onSubmit={submit} className="mt-10 space-y-6 rounded-3xl bg-white p-6 shadow-sm md:p-10"><div className="grid gap-5 sm:grid-cols-2"><label>昵称（可选）<input name="name" className="field" placeholder="怎么称呼你" /></label><label>性别（可选）<select name="gender" className="field"><option value="">不填写</option><option>女</option><option>男</option><option>其他</option></select></label></div><label>历法<select name="calendar" className="field"><option value="gregorian">公历</option><option value="lunar">农历（当前输入仍需对应公历日期）</option></select></label><div className="grid gap-5 sm:grid-cols-2"><label>出生日期 *<input required name="birthDate" type="date" className="field" /></label><label>出生时间<input name="birthTime" type="time" className="field" disabled={false} /></label></div><label className="flex items-center gap-3 text-sm"><input name="unknownTime" type="checkbox" /> 我不知道出生时间（将来可进入校准流程）</label><div className="grid gap-5 sm:grid-cols-2"><label>国家<input name="country" className="field" placeholder="中国" /></label><label>省 / 州<input name="state" className="field" placeholder="广东省" /></label><label>城市<input name="city" className="field" placeholder="深圳市" /></label><label>出生地点<input name="place" className="field" placeholder="医院或城区（可选）" /></label></div><label className="flex items-center gap-3 text-sm"><input name="trueSolarTime" type="checkbox" /> 使用真太阳时（结果会保留原始时间）</label>{error && <p className="text-sm text-red-700">{error}</p>}<button className="w-full rounded-xl bg-ink px-5 py-4 font-medium text-white hover:opacity-90">生成我的基础盘</button></form></div></main>;
}
